[package]
name = "Cuscuta"
version = "0.1.0"
authors = ["Rory McCann <rcm71@pitt.edu>", "Lukas Finn <lef74@pitt.edu>"]
edition = "2021"

[dependencies]
bevy = "=0.14.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
flexbuffers = "2.0.0"
