[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Rory McCann <rcm71@pitt.edu>", "Lukas Finn <lef74@pitt.edu>"]


[dependencies]
bevy = "=0.14.0"
rand = "0.8"
serde = {version = "1.0" , features = ["derive"] }
flexbuffers = "2.0.0"
library = { path = "../library" }